name: Deploy to GitHub Pages

on:
  push:
    branches: [deploy]

permissions:
  contents: write # Required to deploy to GitHub Pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true
    
      - name: Upload 'site/' folder
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
              